"use client";

import { motion } from "framer-motion";
import { Sparkles, FileText, Clock3, Calendar, CheckCircle2, LineChart, ShieldCheck } from "lucide-react";
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

const features = [
  {
    icon: Sparkles,
    title: "AI Study Assistant",
    description: "Get smart topic summaries, mock quiz generation, and custom study plans generated by AI models.",
    color: "from-cyan-400 to-blue-500"
  },
  {
    icon: FileText,
    title: "Lecture Notes",
    description: "Capture formatted lecture notes, catalog tags, and view live Markdown compiler renders in real time.",
    color: "from-amber-400 to-orange-500"
  },
  {
    icon: Clock3,
    title: "Focus Mode",
    description: "Work with highly configurable Pomodoro focus timers, rainforest audio loops, and detailed history loggers.",
    color: "from-emerald-400 to-teal-500"
  },
  {
    icon: Calendar,
    title: "Exam Planners",
    description: "Track upcoming midterms and quizzes with target grades, course coverage details, and date notifications.",
    color: "from-fuchsia-400 to-purple-500"
  },
  {
    icon: CheckCircle2,
    title: "Coursework Tasks",
    description: "Organize academic deadlines in a prioritized list, complete with subject tags, credits, and estimations.",
    color: "from-indigo-400 to-blue-500"
  },
  {
    icon: LineChart,
    title: "Detailed Analytics",
    description: "See daily study hours, completed task ratios, weekly summaries, and custom productivity ratings.",
    color: "from-rose-400 to-pink-500"
  },
  {
    icon: ShieldCheck,
    title: "Admin Panel Control",
    description: "Manage global user parameters, student feedback trackers, active announcements, and database configurations.",
    color: "from-violet-400 to-purple-500"
  }
];

export function Features() {
  return (
    <section id="features" className="px-4 py-24 sm:px-6 lg:px-8 relative overflow-hidden bg-slate-950/40 isolate">
      {/* Visual background lights */}
      <div className="absolute left-1/3 top-1/4 h-80 w-80 rounded-full bg-fuchsia-500/5 blur-[120px] z-0" />
      <div className="absolute right-1/4 bottom-1/4 h-80 w-80 rounded-full bg-cyan-500/5 blur-[120px] z-0" />

      <div className="mx-auto max-w-7xl relative z-10">
        <div className="text-center max-w-3xl mx-auto mb-16 space-y-4">
          <motion.p
            initial={{ opacity: 0, y: 10 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-10%" }}
            className="text-[10px] uppercase font-bold tracking-[0.35em] text-cyan-300"
          >
            System capabilities
          </motion.p>
          <motion.h2
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-10%" }}
            transition={{ duration: 0.6 }}
            className="font-display text-3xl font-extrabold text-white sm:text-4xl lg:text-5xl"
          >
            Everything you need in one polished student workspace.
          </motion.h2>
          <motion.p
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-10%" }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="text-slate-400 text-sm sm:text-base max-w-2xl mx-auto"
          >
            Ditch the chaos of multiple student spreadsheets and apps. CogniFlow integrates focus, tasks, notes, and metrics inside a single premium interface.
          </motion.p>
        </div>

        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-10%" }}
              transition={{ duration: 0.5, delay: index * 0.04 }}
            >
              <Card className="h-full border border-white/5 bg-white/5 shadow-md shadow-slate-950/20 backdrop-blur-md transition-all duration-300 hover:-translate-y-1 hover:border-white/10 hover:bg-white/10 group cursor-default">
                <CardHeader className="space-y-4 p-6">
                  <div className={`flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br ${feature.color} text-slate-950 font-bold shadow-md shadow-cyan-950/10`}>
                    <feature.icon className="h-5 w-5" />
                  </div>
                  <CardTitle className="text-xl font-bold text-white group-hover:text-cyan-300 transition duration-300">{feature.title}</CardTitle>
                  <CardDescription className="text-xs sm:text-sm leading-relaxed text-slate-400">{feature.description}</CardDescription>
                </CardHeader>
              </Card>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
